### ISSUE TITLE
wrong italian translation

### ISSUE THREAD

**Issue by sound-code** [OpenSlides/tinymce-i18n#4]
Hi,
just to let you know that there is a wrong translation for a label, precisesly in it.js : 

https://github.com/OpenSlides/tinymce-i18n/blob/master/langs/it.js#L216

it should be "View": "Visualizza"  (double z)

thanks a lot!!

G

**Comment by emanuelschuetze** [comment]
@sound-code We just host the i18n file for bower. We do not coordinate the translations. Please check if this typo is already fixed in the upstream translation plattform on http://archive.tinymce.com/i18n/. If yes we can update the it.js file. Maybe you can make a pull request?
Or better: Bring the tinymce team to provide the translation files via bower. The we would close this (temporary) repository. Thanks.

**Comment by sound-code** [comment]
ok, maybe I will do a pull request?

**Comment by emanuelschuetze** [comment]
yes, please

**Comment by emanuelschuetze** [comment]
Fixed with #5
